name: Ruby

on:
  push:
    branches:
    - main

jobs:
  run_spec:
    name: Run spec
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.0.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.x

    - name: Rspec Test
      run: |
        gem install bundler
        bundle install --path vendor/bundle
        bundle exec rspec
